[workspace]
allow_dirty = true
# dependencies_update = false # run `cargo update`
git_release_enable = false
git_release_latest = false

[[package]]
name = "openstack_sdk"
git_release_enable = true
version_group = "sdks"

[[package]]
name = "openstack_cli"
changelog_include = ["openstack_sdk"]
git_release_enable = true
version_group = "bins"

[[package]]
name = "openstack_tui"
changelog_include = ["openstack_tui"]
git_release_enable = true
version_group = "bins"

[[package]]
name = "openstack_types"
git_release_enable = true
version_group = "sdks"
