[files]
extend-exclude = ["openstack_sdk/static/service-types.json"]
ignore-hidden = true
ignore-files = true
ignore-dot = true
ignore-vcs = true
ignore-global = true
ignore-parent = true

[default]
binary = false
check-filename = true
check-file = true
unicode = true
ignore-hex = true
identifier-leading-digits = false
locale = "en"
extend-ignore-identifiers-re = []
extend-ignore-words-re = []
extend-ignore-re = []

[default.extend-identifiers]

[default.extend-words]
ro = "ro"
ratatui = "ratatui"

[type.rust]
extend-glob = []
extend-ignore-identifiers-re = []
extend-ignore-words-re = []
extend-ignore-re = []

[type.rust.extend-identifiers]
flate2 = "flate2"
wher = "wher"

[type.rust.extend-words]
ro = "ro"
ser = "ser"
typ = "typ"

[type.sh]
extend-glob = []
extend-ignore-identifiers-re = []
extend-ignore-words-re = []
extend-ignore-re = []

[type.sh.extend-identifiers]
ot = "ot"
stap = "stap"

[type.sh.extend-words]

[type.jl]
extend-glob = []
extend-ignore-identifiers-re = []
extend-ignore-words-re = []
extend-ignore-re = []

[type.jl.extend-identifiers]

[type.jl.extend-words]
modul = "modul"
egal = "egal"
egals = "egals"
usig = "usig"

[type.vimscript]
extend-glob = []
extend-ignore-identifiers-re = []
extend-ignore-words-re = []
extend-ignore-re = []

[type.vimscript.extend-identifiers]
windo = "windo"

[type.vimscript.extend-words]

[type.css]
extend-glob = []
extend-ignore-identifiers-re = []
extend-ignore-words-re = []
extend-ignore-re = []

[type.css.extend-identifiers]
nd = "nd"

[type.css.extend-words]

[type.py]
extend-glob = []
extend-ignore-identifiers-re = []
extend-ignore-words-re = []
extend-ignore-re = []

[type.py.extend-identifiers]
NDArray = "NDArray"

[type.py.extend-words]

[type.cert]
extend-glob = []
check-file = false
extend-ignore-identifiers-re = []
extend-ignore-words-re = []
extend-ignore-re = []

[type.cert.extend-identifiers]

[type.cert.extend-words]

[type.man]
extend-glob = []
extend-ignore-identifiers-re = []
extend-ignore-words-re = []
extend-ignore-re = []

[type.man.extend-identifiers]
Nd = "Nd"

[type.man.extend-words]

[type.lock]
extend-glob = []
check-file = false
extend-ignore-identifiers-re = []
extend-ignore-words-re = []
extend-ignore-re = []

[type.lock.extend-identifiers]

[type.lock.extend-words]
